### ISSUE TITLE
Add node>=4 in package.json or not use arrow function

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-nbt#10]
https://github.com/1b8/schematic/issues/4

**Comment by 1b8** [comment]
ProtoDef also uses ES6 features, such as the `class` syntactic sugar and function arrows.

**Comment by rom1504** [comment]
@1b8 protodef uses babel to compile to es5 so it is compatible with node >=0.12

**Comment by 1b8** [comment]
Ah.

**Comment by rom1504** [comment]
done
