### ISSUE TITLE
mcpe 0.16 support 'varint'

### ISSUE THREAD

**Issue by mhsjlw** [PrismarineJS/prismarine-nbt#15]
> \<gurun\> talked to mojang today. The NBT for items, chunks and other stuff is a mess right now, even for them. They ARE moving towards all of it going over the wire to be VarInt style, but right now .. it's totally a mix. ​

I present you, the new specification!
`varint` is **always** little-endian (finally they can settle on something)
we also need `varlong`, I don't think ProtoDef has that

Here is an implementation in C# https://github.com/NiclasOlofsson/fNbt/commit/61619ac593fe78c992a292850b40b44cc7d43ccc
Strings are `varint` prefixed, and there can be `varint32` and `varint64` fields it looks like
- All ints are now replaced with `varints`
- We will need to actually separate the implementations

**Comment by rom1504** [comment]
feel free to start writing a .json for this.
Once it can decode mcpe nbt properly, we'll see how to integrate it properly here. (Would be useful to have some mcpe nbt example files !)

**Comment by mhsjlw** [comment]
Ah yeah, I'll ask around and see if I can grab a 0.16 NBT file, or if I can generate one myself

**Comment by rom1504** [comment]
would be useful to put infos here
* [ ] link to nbt example
* [ ] description of the new format

**Comment by mhsjlw** [comment]
#18
