### ISSUE TITLE
Write Compressed NBT Files

### ISSUE THREAD

**Issue by CheeseL0ver** [PrismarineJS/prismarine-nbt#27]
I know there is a method to write uncompressed data but is there any support for compressed data?

**Comment by rom1504** [comment]
You can compress it using node https://nodejs.org/api/zlib.html module

**Comment by CheeseL0ver** [comment]
I see. So the answer is the library does not support writing compressed data, but the recommendation is to use the writeUncompressed function and then compress that output using a separate module. Thank you! @rom1504
