### ISSUE TITLE
SyntaxError: Unexpected token '='

### ISSUE THREAD

**Issue by StavZ** [PrismarineJS/prismarine-nbt#29]
![image](https://user-images.githubusercontent.com/36641973/86532405-52378000-bed2-11ea-8c9b-889b976959d0.png)
An error occurs every time when i trying launch my discord bot, but when i comment these two lines bot is launching.
![image](https://user-images.githubusercontent.com/36641973/86532432-90cd3a80-bed2-11ea-93ef-11aa51b92ba8.png)

**Comment by StavZ** [comment]
Now i tried remove all from `nbt.json` and it helped.

**Comment by B1a7e** [comment]
Did you fix it?
