### ISSUE TITLE
TagType enum cannot be imported

### ISSUE THREAD

**Issue by McJeffr** [PrismarineJS/prismarine-nbt#40]
Hi!

There is an `index.d.ts` file attached the package, which is very useful for implementations that use TypeScript. These types work fairly nice, with the exception of one: the `TagType` enum. TypeScript enums are not exported properly when defined in a `d.ts` file, as they are not transpiled to the `index.js` file, nor are they a declared type using `type`.

See the example below:
```typescript
import { TagType } from "prismarine-nbt";

console.log(TagType); // "undefined"
console.log(TagType.Int); // "TypeError: Cannot read property 'Int' of undefined"
```

The issue here is that an enum will be transpiled to JavaScript as it describes some functionality. However, the contents of the `.d.ts` file are not transpiled. See for example this [Reddit post](https://www.reddit.com/r/typescript/comments/dp7zd5/enum_or_enumlike_type_in_a_declaration_file/) on the topic. This issue makes it difficult to use the TypeScript typings effectively, as the `Tags` are indexed by the enum, e.g. `Tags[TagType.Int]`.

A (temporary) fix that I have employed is to copy the enum over to a `.ts` file in my own project. However, it'd be nicer to be able to use the one provided by the package.

**Comment by extremeheat** [comment]
Yeah, looks like the enum there is missing a JS implementation, it should be simple to add in a TagType map export in JS.

**Comment by McJeffr** [comment]
Possibly, my TypeScript transpiled the `TagType` enum to
```typescript
var TagType;
(function (TagType) {
    TagType["Byte"] = "byte";
    TagType["Short"] = "short";
    TagType["Int"] = "int";
    TagType["Long"] = "long";
    TagType["Float"] = "float";
    TagType["Double"] = "double";
    TagType["ByteArray"] = "byteArray";
    TagType["String"] = "string";
    TagType["List"] = "list";
    TagType["Compound"] = "compound";
    TagType["IntArray"] = "intArray";
    TagType["LongArray"] = "longArray";
})(TagType || (TagType = {}));
```

**Comment by extremeheat** [comment]
it can be simplified to:
```js
const TagType = {
  Byte: 'byte',
  Short: 'short',
  Int: 'int',
  Long: 'long',
  Float: 'float',
  Double: 'double',
  ByteArray: 'byteArray',
  String: 'string',
  List: 'list',
  Compound: 'compound',
  IntArray: 'intArray',
  LongArray: 'longArray'
}
```

**Comment by extremeheat** [comment]
I think the current PR is ok. But what about a const enum in typescript definitions instead? Do you think that would work?

**Comment by McJeffr** [comment]
Hm, good question. I am not too sure, but I can test it later and see.
