### ISSUE TITLE
Frontend Web Support

### ISSUE THREAD

**Issue by Offroaders123** [PrismarineJS/prismarine-nbt#56]
I found this project not too long ago, and it works really well! I tried using Webpack to compile it for use on the frontend web by itself, but I had no success there. I also found the [NBT.js](https://github.com/sjmulder/nbt-js) library by sjmulder, and it also works really nicely. I have hopes to open and edit Bedrock formatted NBT files on the frontend web, for which their project works with the web out of the box, but their project unfortunately doesn't have support for the Bedrock NBT format. After those, I have started looking into making my own library for parsing NBT because I couldn't find one out there that quite suits my requirements yet.

Is it possible for you could make Prismarine-NBT work on the web in a more out-of-the-box fashion? If not, would you mind showing me the things that you learned about the Bedrock NBT and how to be able to parse it, compared to the Java format? I'd be happy to make my own fork of sjmulder's NBT.js and add Bedrock support, as theirs works really well too. I'm just having a harder time finding documentation about the Bedrock NBT format, as not many parsers support it, and yours is one of the only ones I've found that supports both formats, and is written in JavaScript.

Thanks a lot!

**Comment by extremeheat** [comment]
For webpack usage, see an example configuration here: https://github.com/PrismarineJS/prismarine-web-client/blob/master/webpack.common.js

If you want something that works out of the box for node to browser you can try browserify:  For a web bundle with browserify (after you ran npm install prismarine-nbt in your project):

```
npx browserify -r prismarine-nbt -r buffer -o pnbt.js
```

**Comment by Offroaders123** [comment]
Awesome, thanks!
I'm still having some trouble getting it working with these too. I think possibly I need to learn more about bundlers, maybe it's something I'm missing that's causing it not to bundle correctly.
