### ISSUE TITLE
[Help Wanted] Webpack Unexpected Token

### ISSUE THREAD

**Issue by Clemintina** [PrismarineJS/prismarine-nbt#68]
**Issue**: Unable to use this module with Webpack 5.

**Node**: 18.2.0, Tried with 17.4.0 as well
**Package Manager**: Yarn

**Package versions**: 

Prismarine-nbt: 2.2.1,
Webpack: 5.72.0,
Electron: 19.0.4
React: 18.2.0
React Dom: 18.2.0

**Console Message**:

Electron Forge was terminated:
ModuleBuildError: Module build failed (from ./node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js):
SyntaxError: Unexpected token (169:23)

**Renderer Message**:

Syntax error: Unexpected token (169:23)
node_modules/prismarine-nbt/nbt.js

**Comment by extremeheat** [comment]
Try to update your dependencies and take a look at the webpack config here - https://github.com/PrismarineJS/prismarine-web-client/blob/master/webpack.common.js
