### ISSUE TITLE
Mixed list; string as compound

### ISSUE THREAD

**Issue by Gjum** [PrismarineJS/prismarine-nbt#97]
In the 1.20 protocol, most chat is represented as NBT. Chat has several situations (translate, extra) where an array can contain either more chat elements, or simple strings. In this case, Mojang represents strings as compounds with a single `""` key:

<details>
<summary>Show example</summary>
<pre>
{
	"type": "compound",
	"value": {
		"translate": {
			"type": "string",
			"value": "commands.teleport.success.location.single"
		},
		"with": {
			"type": "list",
			"value": {
				"type": "compound",
				"value": [
					{ "text": { "type": "string", "value": "PlayerName" } },
					{ "": { "type": "string", "value": "-123.5" } },
					{ "": { "type": "string", "value": "63.5" } },
					{ "": { "type": "string", "value": "-45.5" } }
				]
			}
		}
	}
}
</pre>
</details>

My use case is converting the chat NBT to the old format: `new ChatMessage(NBT.simplify(packet.message))`

To solve this, `simplify()` could convert `{ "": { "type": "string", "value": "some text" } }` to `"some text"`.

This would also eliminate the need for special handling via `processNbtMessage` etc.

Related:
https://github.com/PrismarineJS/prismarine-chat/pull/103
https://github.com/PrismarineJS/prismarine-chat/issues/104

**Comment by extremeheat** [comment]
I guess it could, but this doesn't seem correct in the sense that simplify is no longer removing type wrappers but changing the underlying data structure. This could be a problem as it breaks creating a potential reverse simplify() function in the future.

**Comment by Gjum** [comment]
I consider the `{"":...}` hack to be a (quirky) type wrapper (as NBT does not allow mixed types in an array in any way compatible with the standard type wrapping).
It can be undone by noticing that the array contains both objects and strings in this case, and converting it to a compound array encoding strings with the same `{"":...}`.
By the way, how will a reverse simplify() function decide whether an array of (incidentally) integer values should be turned back into an (original) array of floats? Maybe some similar approach applies here as well.

**Comment by extremeheat** [comment]
Related to what I mentioned is #39. Turning to string is a completely different type than an object with one key in it.

**Comment by Gjum** [comment]
Thank you for clarifying. In that case I agree that it may be better to strictly stick with the NBT spec here and deal with the use of the hack one level higher in prismarine-chat and wherever else it may show up.
